<x-admin-layout title="Dashboard">
    <section class="admin-dashboard-hero"><div><span class="eyebrow">PROGRAM COMMAND CENTRE</span><h2>Good day, {{ explode(' ',auth('admin')->user()->name)[0] }}.</h2><p>Monitor customers, revenue, subscriptions and claims from one place.</p></div><div class="admin-dashboard-hero__actions"><a href="{{ route('admin.reports.index') }}" class="button button--cancel">Export reports</a><a href="{{ route('admin.plans.create') }}" class="button button--dark">Add new plan <span>+</span></a></div></section>

    <div class="admin-stats admin-dashboard-stats">
        <article><span class="stat-icon stat-blue">♙</span><div><p>Total customers</p><b>{{ number_format($customers) }}</b><small>+{{ $newCustomers }} in the last 30 days</small></div></article>
        <article><span class="stat-icon stat-green">◇</span><div><p>Active subscriptions</p><b>{{ number_format($subscriptions) }}</b><small>{{ $expiringSubscriptions }} expire within 30 days</small></div></article>
        <article><span class="stat-icon stat-gold">▤</span><div><p>Pending claims</p><b>{{ number_format($pendingClaims) }}</b><small>Require an admin decision</small></div></article>
        <article><span class="stat-icon stat-red">$</span><div><p>Paid revenue</p><b>${{ number_format($revenue/100,2) }}</b><small>Across completed payments</small></div></article>
    </div>

    <section class="dashboard-analytics-grid">
        <article class="panel analytics-card"><div class="analytics-heading"><div><span class="eyebrow">CLAIM ACTIVITY</span><h3>Claims over six months</h3></div><a href="{{ route('admin.claims.index') }}">View all →</a></div><div class="bar-chart" aria-label="Claims by month">@foreach($months as $month)<div class="bar-chart__column"><b>{{ $month['claims'] }}</b><span style="height:{{ max(8,round(($month['claims']/$maxMonthlyClaims)*100)) }}%"></span><small>{{ $month['label'] }}</small></div>@endforeach</div></article>
        <article class="panel analytics-card"><div class="analytics-heading"><div><span class="eyebrow">CLAIM OUTCOMES</span><h3>Current status mix</h3></div></div><div class="status-visual"><div class="status-donut" style="--approved:{{ $approvedDegrees }}deg;--pending:{{ $pendingDegrees }}deg"><div><b>{{ $claimStatuses->sum() }}</b><small>Total claims</small></div></div><div class="status-legend"><span><i class="approved"></i>Approved <b>{{ $claimStatuses['approved'] }}</b></span><span><i class="pending"></i>Pending <b>{{ $claimStatuses['pending'] }}</b></span><span><i class="disapproved"></i>Disapproved <b>{{ $claimStatuses['disapproved'] }}</b></span></div></div></article>
    </section>

    <section class="dashboard-activity-grid">
        <article class="panel activity-panel"><div class="analytics-heading"><div><span class="eyebrow">LATEST CLAIMS</span><h3>Recent claim requests</h3></div><a href="{{ route('admin.claims.index') }}">Review claims →</a></div><div class="activity-list">@forelse($recentClaims as $claim)<a href="{{ route('admin.claims.show',$claim) }}"><span class="activity-icon">▣</span><span class="person-details"><b>{{ $claim->user->name }}</b><small>{{ $claim->user->email }}</small></span><span class="activity-meta"><b>{{ $claim->claim_number }}</b><small>{{ $claim->created_at->diffForHumans() }}</small></span><span class="claim-status claim-status--{{ $claim->status }}">{{ ucfirst($claim->status) }}</span></a>@empty<p class="activity-empty">No claims have been submitted yet.</p>@endforelse</div></article>
        <article class="panel activity-panel"><div class="analytics-heading"><div><span class="eyebrow">LATEST PAYMENTS</span><h3>Recent transactions</h3></div><a href="{{ route('admin.payments.index') }}">View payments →</a></div><div class="activity-list">@forelse($recentPayments as $payment)<a href="{{ route('admin.payments.show',$payment) }}"><span class="activity-icon activity-icon--money">$</span><span class="person-details"><b>{{ $payment->user->name }}</b><small>{{ $payment->user->email }}</small></span><span class="activity-meta"><b>{{ $payment->amount ? '$'.number_format($payment->amount/100,2) : 'Free' }}</b><small>{{ $payment->plan->name }}</small></span><span class="claim-status claim-status--{{ $payment->status==='paid'?'approved':'pending' }}">{{ ucfirst(str_replace('_',' ',$payment->status)) }}</span></a>@empty<p class="activity-empty">No payment records yet.</p>@endforelse</div></article>
    </section>
</x-admin-layout>
