<x-admin-layout title="Claim Review">
    <section class="form-page-heading"><a href="{{ route('admin.claims.index') }}">← Back to claims</a><h2>Claim {{ $claim->claim_number }}</h2><p>Submitted {{ $claim->created_at->format('d M Y, h:i A') }}</p></section>
    <div class="admin-claim-grid"><section class="panel"><div class="claim-meta-grid"><div><span>CUSTOMER</span><b>{{ $claim->user->name }}</b><small>{{ $claim->user->email }} · {{ $claim->user->phone ?: 'No phone' }}</small></div><div><span>WARRANTY CODE</span><b class="code-value">{{ $claim->warrantyCode?->code ?: '—' }}</b></div><div><span>PLAN</span><b>{{ $claim->subscription->plan->name }}</b><small>Valid until {{ $claim->subscription->ends_at->format('d M Y') }}</small></div><div class="vehicle-meta"><span>VEHICLE</span><b>{{ trim($claim->vehicle_make.' '.$claim->vehicle_model) ?: 'Not provided' }}</b><small>{{ $claim->registration_number ?: '—' }}{{ $claim->vehicle_year ? ' · '.$claim->vehicle_year : '' }}</small></div><div><span>MODEL AREA LIMIT</span><b>{{ $claim->model_coverage_sqm ? number_format($claim->model_coverage_sqm, 2).' m²' : 'Not recorded' }}</b></div><div><span>STATUS</span><b class="claim-status claim-status--{{ $claim->status }}">{{ ucfirst($claim->status) }}</b></div>@if($claim->available_date)<div><span>CUSTOMER AVAILABLE DATE</span><b>{{ $claim->available_date->format('d M Y') }}</b></div>@endif @if($claim->booking_date)<div><span>BOOKING DATE</span><b>{{ $claim->booking_date->format('d M Y') }}</b></div>@endif</div>
        <div class="admin-panel-review"><div class="claim-model-visual">
            @if($vehiclePhotoUrl)
                <div class="claim-model-visual__stage"><img src="{{ $vehiclePhotoUrl }}" alt="{{ $claim->vehicle_make }} {{ $claim->vehicle_model }} model photo">
                    @if($selectedAreas->isNotEmpty())<svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Customer selected vehicle panels">@foreach($selectedAreas as $area)<polygon points="{{ collect($area['points'])->map(fn ($point) => $point['x'].','.$point['y'])->implode(' ') }}"><title>{{ $area['name'] }}</title></polygon>@endforeach</svg>@endif
                </div>
                <small>{{ $selectedAreas->isNotEmpty() ? 'Selected panel areas on the model photo' : 'Model photo · selected panels listed alongside' }}</small>
            @else
                <div class="model-photo__pending">Model photo unavailable</div><small>Selected panels are listed alongside.</small>
            @endif
        </div><div><span class="eyebrow">CUSTOMER SELECTED PANELS</span><h3>{{ count($claim->panels) }} damaged {{ Str::plural('panel', count($claim->panels)) }}</h3><ul>@foreach($claim->panels as $panel)@php($detail = collect($claim->panel_details ?? [])->firstWhere('key', $panel))<li>{{ $detail['name'] ?? $panels[$panel] ?? $panel }}</li>@endforeach</ul></div></div>@if($claim->description)<div class="claim-description"><span class="eyebrow">CUSTOMER NOTES</span><p>{{ $claim->description }}</p></div>@endif<span class="eyebrow">DAMAGE PHOTOS AND VIDEOS</span><div class="claim-photo-grid admin-photos">@foreach($claim->photos as $index=>$photo)@if($claim->isVideoEvidence($index))<video controls preload="metadata" src="{{ route('admin.claims.photo',[$claim,$index]) }}" aria-label="Damage video {{ $index+1 }}"></video>@else<a href="{{ route('admin.claims.photo',[$claim,$index]) }}" target="_blank"><img src="{{ route('admin.claims.photo',[$claim,$index]) }}" alt="Damage evidence {{ $index+1 }}"></a>@endif @endforeach</div></section>
        <aside class="panel decision-card"><span class="eyebrow">REVIEW DECISION</span><h3>Approve or decline</h3><form method="POST" action="{{ route('admin.claims.update',$claim) }}">@csrf @method('PUT')<div class="field"><label>Booking date <small>Customer date is filled in automatically</small></label><div class="field__control"><input type="date" name="booking_date" min="{{ now()->toDateString() }}" value="{{ old('booking_date',$claim->booking_date?->toDateString() ?? ($claim->available_date && $claim->available_date->gte(today()) ? $claim->available_date->toDateString() : '')) }}"></div>@error('booking_date')<p class="field__error">{{ $message }}</p>@enderror</div><div class="field"><label>Admin notes / decline reason</label><textarea name="admin_notes" rows="7" placeholder="A reason is required when declining a claim.">{{ old('admin_notes',$claim->admin_notes) }}</textarea>@error('admin_notes')<p class="field__error">{{ $message }}</p>@enderror</div><div class="decision-actions"><button class="button button--approve" name="status" value="approved">✓ Approve</button><button class="button button--decline" name="status" value="disapproved">× Decline</button></div></form><form method="POST" action="{{ route('admin.claims.destroy',$claim) }}" onsubmit="return confirm('Permanently delete this claim?')">@csrf @method('DELETE')<button class="danger-link">× Delete claim</button></form></aside>
    </div>
</x-admin-layout>
