<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Complete purchase · Proflect</title>@vite(['resources/css/app.css','resources/js/app.js'])<script src="https://checkout.razorpay.com/v1/checkout.js" defer></script></head>
<body class="checkout-body"><header class="simple-header"><x-brand/><span>Secure checkout</span></header><main class="checkout-shell">
<div class="stepper"><span class="done"><i>✓</i>Choose a plan</span><b></b><span class="active"><i>2</i>Checkout</span><b></b><span><i>3</i>Protected</span></div>
<a href="{{ route('subscription.index') }}" class="back-link">← Back to plans</a><div class="checkout-grid"><section><span class="eyebrow">COMPLETE YOUR PURCHASE</span><h1>Protection is one step away.</h1><p class="checkout-lead">Review your plan and pay securely with Razorpay.</p>
<div class="pay-method"><div class="pay-method__radio">●</div><div><b>Razorpay Secure Checkout</b><p>Cards, UPI, netbanking and supported wallets</p></div><strong>Razorpay</strong></div>
<div class="secure-box"><span>♙</span><p><b>Safe and encrypted payment</b><br>Payment details are collected directly by Razorpay and never stored by Proflect.</p></div>
<div id="payment-error" class="alert payment-error" hidden></div>
<button class="button button--primary pay-now" data-payment-button data-plan-id="{{ $plan->id }}" data-order-url="{{ route('payments.order') }}" data-verify-url="{{ route('payments.verify') }}" data-customer-name="{{ auth()->user()->name }}" data-customer-email="{{ auth()->user()->email }}">Pay {{ $plan->formatted_price }} securely <span>→</span></button>
<p class="razorpay-config-note">Razorpay API keys must be configured before a payment can open.</p></section>
<aside class="order-card"><span class="eyebrow">ORDER SUMMARY</span><div class="order-plan"><span class="plan-badge">{{ strtoupper(substr($plan->name,0,1)) }}</span><div><h3>{{ $plan->name }}</h3><p>{{ $plan->duration_years }} years · {{ rtrim(rtrim($plan->coverage_sqm,'0'),'.') }} m² coverage</p></div></div><ul>@foreach($plan->features ?? [] as $feature)<li>✓ {{ $feature }}</li>@endforeach</ul><div class="price-line"><span>Plan price</span><b>{{ $plan->formatted_price }}</b></div><div class="price-line"><span>GST</span><b>Included</b></div><div class="price-line total"><span>Total payable</span><b>{{ $plan->formatted_price }}</b></div><small>One-time payment. No auto-renewal.</small></aside></div></main></body></html>
