<x-customer-layout title="Submit a Claim">
<section class="claim-wizard panel" data-claim-wizard>
    <div class="claim-heading"><div><span class="eyebrow">CLAIM REQUEST</span><h2>Tell us what was damaged.</h2><p>Select every affected panel, add clear photos, then review before submitting.</p></div><span class="claim-plan">{{ $subscription->plan->name }}<small>Valid until {{ $subscription->ends_at->format('d M Y') }}</small></span></div>
    <div class="claim-steps"><button type="button" class="active" data-step-target="1"><i>1</i><span>Select panels</span></button><b></b><button type="button" data-step-target="2"><i>2</i><span>Upload photos</span></button><b></b><button type="button" data-step-target="3"><i>3</i><span>Review</span></button></div>
    <form method="POST" action="{{ route('claims.store') }}" enctype="multipart/form-data" novalidate data-maximum-vehicle-year="{{ now()->year + 1 }}">@csrf
        <section class="claim-step active" data-step="1"><div class="vehicle-fields"><div class="vehicle-fields__heading"><span>🚗</span><div><h3>Vehicle details</h3><p>Add the vehicle connected to this damage.</p></div></div><div class="field-grid"><div class="field"><label>Vehicle make</label><div class="field__control"><input name="vehicle_make" value="{{ old('vehicle_make') }}" placeholder="e.g. Toyota" required></div></div><div class="field"><label>Vehicle model</label><div class="field__control"><input name="vehicle_model" value="{{ old('vehicle_model') }}" placeholder="e.g. Fortuner" required></div></div><div class="field"><label>Registration number</label><div class="field__control"><input name="registration_number" value="{{ old('registration_number') }}" placeholder="e.g. MH12AB1234" required></div></div><div class="field"><label>Model year <small>Optional</small></label><div class="field__control"><input type="number" name="vehicle_year" min="1950" max="{{ now()->year+1 }}" value="{{ old('vehicle_year') }}" placeholder="e.g. 2024"></div></div></div></div><div class="panel-select-grid">
            <x-vehicle-diagram interactive />
            <div class="panel-options"><h3>Select damaged panels</h3><p>Choose one or more areas.</p>@foreach($panels as $value=>$label)<label><input type="checkbox" name="panels[]" value="{{ $value }}" data-panel-input><span>{{ $label }}</span></label>@endforeach</div>
        </div><div class="wizard-actions"><a href="{{ route('dashboard') }}" class="button button--ghost">Cancel</a><button type="button" class="button button--dark" data-next>Next <span>→</span></button></div></section>
        <section class="claim-step" data-step="2"><div class="upload-stage"><span class="upload-icon">⇧</span><h3>Upload damage photos</h3><p>Add 1 to 6 clear JPG, PNG or WebP photos. Each file can be up to 5 MB.</p><label class="button button--dark upload-button">Choose photos<input type="file" name="photos[]" accept="image/jpeg,image/png,image/webp" multiple data-photo-input></label><div class="photo-previews" data-photo-previews></div><div class="field"><label>Additional details <small>Optional</small></label><textarea name="description" rows="4" placeholder="Tell us how the damage happened or add anything our review team should know.">{{ old('description') }}</textarea></div></div><div class="wizard-actions"><button type="button" class="button button--ghost" data-prev>← Previous</button><button type="button" class="button button--dark" data-next>Next <span>→</span></button></div></section>
        <section class="claim-step" data-step="3"><div class="review-hero"><span class="review-hero__icon">✓</span><div><span class="eyebrow">FINAL REVIEW</span><h3>Everything looks ready.</h3><p>Check the journey below before sending your claim to our review team.</p></div></div><div class="review-timeline"><article><i>1</i><div><span>VEHICLE</span><h4 data-review-vehicle>Your vehicle</h4><p data-review-registration></p></div></article><article><i>2</i><div><span>DAMAGED PANELS</span><h4>Selected areas</h4><ul data-review-panels></ul></div></article><article><i>3</i><div><span>PHOTO EVIDENCE</span><h4 data-review-photos>No photos selected</h4><div class="review-photo-strip" data-review-photo-strip></div></div></article><article><i>4</i><div><span>YOUR NOTES</span><h4>Additional information</h4><p data-review-description>No additional details provided.</p></div></article></div><div class="review-notice"><b>Ready to submit?</b><span>After submission, you can follow pending, approved or disapproved status from Claim History.</span></div><div class="wizard-actions"><button type="button" class="button button--ghost" data-prev>← Previous</button><button type="submit" class="button button--primary">Submit claim <span>→</span></button></div></section>
    </form>
</section>
</x-customer-layout>
