<x-customer-layout title="Submit a Claim">
<section class="claim-wizard panel" data-claim-wizard>
    <div class="claim-heading"><div><span class="eyebrow">CLAIM REQUEST</span><h2>Tell us what was damaged.</h2><p>Select every affected panel, add clear photos or video, then review before submitting.</p></div><span class="claim-plan">{{ $subscription->plan->name }}<small>Valid until {{ $subscription->ends_at->format('d M Y') }}</small></span></div>
    <div class="claim-steps"><button type="button" class="active" data-step-target="1"><i>1</i><span>Select panels</span></button><b></b><button type="button" data-step-target="2"><i>2</i><span>Upload evidence</span></button><b></b><button type="button" data-step-target="3"><i>3</i><span>Review</span></button></div>
    <form method="POST" action="{{ route('claims.store') }}" enctype="multipart/form-data" novalidate data-maximum-vehicle-year="{{ now()->year + 1 }}" data-warranty-check-url="{{ route('claims.warranty-code.check') }}" data-catalog-makes-url="{{ url('/catalog/makes') }}" data-catalog-models-url="{{ url('/catalog/models') }}">@csrf
        <script type="application/json" data-old-panels>@json(old('panels', []))</script>
        <section class="claim-step active" data-step="1">
            <div class="warranty-code-field"><div><span class="eyebrow">CLAIM AUTHORISATION</span><h3>Enter your warranty code</h3><p>Each warranty code is valid for one claim only.</p></div><div class="field"><label for="warranty-code">Warranty code</label><div class="field__control" data-warranty-control><input id="warranty-code" name="warranty_code" value="{{ old('warranty_code') }}" placeholder="CLM-260901-ZM9JVS" maxlength="30" autocomplete="off" required></div><p class="warranty-feedback @error('warranty_code') invalid @enderror" data-warranty-feedback aria-live="polite">@error('warranty_code'){{ $message }}@enderror</p></div></div>
            <div class="vehicle-fields"><div class="vehicle-fields__heading"><span>🚗</span><div><h3>Vehicle details</h3><p>Select the vehicle connected to this damage.</p></div></div>
                <div class="field-grid"><div class="field"><label for="vehicle-make">Vehicle make</label><div class="field__control"><select id="vehicle-make" name="vehicle_make_id" required><option value="">Select vehicle make</option>@foreach($vehicleMakes as $make)<option value="{{ $make->id }}" @selected(old('vehicle_make_id') == $make->id)>{{ $make->name }}</option>@endforeach</select></div></div><div class="field"><label for="vehicle-model">Vehicle model</label><div class="field__control"><select id="vehicle-model" name="vehicle_model_id" data-old-model="{{ old('vehicle_model_id') }}" required><option value="">Select vehicle make first</option></select></div></div><div class="field"><label>Registration number</label><div class="field__control"><input name="registration_number" value="{{ old('registration_number') }}" placeholder="e.g. MH12AB1234" required></div></div><div class="field"><label>Model year <small>Optional</small></label><div class="field__control"><input type="number" name="vehicle_year" min="1950" max="{{ now()->year+1 }}" value="{{ old('vehicle_year') }}" placeholder="e.g. 2024"></div></div></div>
                @if($vehicleMakes->isEmpty())<p class="catalog-empty-note">Vehicle options are being prepared. Please contact support before submitting a claim.</p>@else<p class="catalog-help">If your vehicle is missing, contact support. <a href="{{ route('vehicle-data.credits') }}">Catalog coverage</a></p>@endif
            </div>
            <div class="panel-select-grid"><div data-model-photo class="model-photo"><div class="model-photo__pending">Photo pending</div><div class="model-photo__stage" data-model-photo-stage hidden><img alt=""><svg data-model-areas viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Selectable vehicle panels"></svg></div><small>Select a model to see its photo.</small></div><div class="panel-options"><h3>Select damaged panels</h3><p data-model-coverage>Select a vehicle model to see its area limit.</p><div data-model-panels><p class="catalog-empty-note">Select a vehicle model to see its panels.</p></div></div></div>
            <div class="wizard-actions"><a href="{{ route('dashboard') }}" class="button button--ghost">Cancel</a><button type="button" class="button button--dark" data-next>Next <span>→</span></button></div>
        </section>
        <section class="claim-step" data-step="2"><div class="upload-stage"><span class="upload-icon">⇧</span><h3>Upload damage evidence</h3><p>Add 1 to 6 photos or videos. JPG, PNG and WebP photos can be up to 5 MB each; MP4, MOV and WebM videos can be up to 30 MB each. Keep all files together under 35 MB.</p><label class="button button--dark upload-button">Choose photos or videos<input type="file" name="photos[]" accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime,video/webm" multiple data-photo-input></label><div class="photo-previews" data-photo-previews></div><div class="field"><label for="available_date">Your available date <small>Optional</small></label><div class="field__control"><input id="available_date" type="date" name="available_date" min="{{ now()->toDateString() }}" value="{{ old('available_date') }}"></div>@error('available_date')<p class="field__error">{{ $message }}</p>@enderror</div><div class="field"><label>Additional details <small>Optional</small></label><textarea name="description" rows="4" placeholder="Tell us how the damage happened or add anything our review team should know.">{{ old('description') }}</textarea></div></div><div class="wizard-actions"><button type="button" class="button button--ghost" data-prev>← Previous</button><button type="button" class="button button--dark" data-next>Next <span>→</span></button></div></section>
        <section class="claim-step" data-step="3"><div class="review-hero"><span class="review-hero__icon">✓</span><div><span class="eyebrow">FINAL REVIEW</span><h3>Everything looks ready.</h3><p>Check the journey below before sending your claim to our review team.</p></div></div><div class="review-timeline"><article><i>1</i><div><span>VEHICLE</span><h4 data-review-vehicle>Your vehicle</h4><p data-review-registration></p><p data-review-model-limit></p></div></article><article><i>2</i><div><span>DAMAGED PANELS</span><h4>Selected areas</h4><ul data-review-panels></ul></div></article><article><i>3</i><div><span>PHOTO AND VIDEO EVIDENCE</span><h4 data-review-photos>No evidence selected</h4><div class="review-photo-strip" data-review-photo-strip></div></div></article><article><i>4</i><div><span>AVAILABLE DATE AND NOTES</span><h4 data-review-available-date>No available date selected</h4><p data-review-description>No additional details provided.</p></div></article></div><div class="review-notice"><b>Ready to submit?</b><span>After submission, you can follow pending, approved or disapproved status from Claim History.</span></div><div class="wizard-actions"><button type="button" class="button button--ghost" data-prev>← Previous</button><button type="submit" class="button button--primary">Submit claim <span>→</span></button></div></section>
    </form>
</section>
</x-customer-layout>
